name: flutter_login
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  shared_preferences: ^2.3.2
  google_maps_flutter: ^2.9.0
  flutter_polyline_points: ^2.1.0
  location: ^6.0.2
  flutter_markdown: ^0.7.3+2
  fl_chart: ^0.69.0
  fluttertoast: ^8.2.8
  razorpay_flutter: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/start_gif.gif
    - assets/images/home.png
    - assets/images/food.jpeg
    - assets/images/electrical.jpeg
    - assets/images/clothes.jpeg
    - assets/images/accessories.jpeg
    - assets/images/food1.jpg
    - assets/images/food2.jpg
    - assets/images/food3.jpg
    - assets/images/Pizza 1.jpeg
    - assets/images/Pizza 2.jpeg
    - assets/images/pizza3.jpg
    - assets/images/accessories1.jpg
    - assets/images/accessories2.jpg
    - assets/images/accessories3.jpg
    - assets/images/clothes1.jpg
    - assets/images/clothes2.jpg
    - assets/images/clothes3.jpg
    - assets/images/electrical1.jpg
    - assets/images/electrical2.jpg
    - assets/images/electrical3.jpg
    - assets/images/cake1.jpeg
    - assets/images/cake2.jpeg
    - assets/images/cake3.jpg
    - assets/images/burger 1.jpeg
    - assets/images/burger 2.jpeg
    - assets/images/burger 3.jpg
    - assets/images/sunglass1.jpeg
    - assets/images/sunglass2.jpeg
    - assets/images/sunglass3.jpg
    - assets/images/watch 1.jpeg
    - assets/images/watch 2.jpeg
    - assets/images/watch3.jpg
    - assets/images/cap 1.jpeg
    - assets/images/cap2.jpg
    - assets/images/cap3.jpg
    - assets/images/t-shirt3.jpg
    - assets/images/bulb3.jpg
    - assets/images/pant3.jpg






